/**
 * Generates UI + lesson locale files from compact data (merged onto English).
 * Run: node scripts/generate-locales.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(__dirname, '../src/i18n/locales');

/** @type {Record<string, any>} */
const packs = {
  es: {
    common: { back: 'Atrás', close: 'Cerrar', continue: 'Continuar', next: 'Siguiente', loading: 'Cargando…', tryAgain: 'Inténtalo de nuevo', free: 'Gratis', pro: 'Pro', cancel: 'Cancelar' },
    welcome: { tagline: 'Español para principiantes — rápido, claro y divertido.', getStarted: 'Empezar', haveAccount: 'Ya tengo cuenta', tryGuest: 'Probar sin cuenta', legal: 'Desde precio local al mes o al año. Cancela cuando quieras en App Store.', chooseLanguage: 'Idioma de la app' },
    auth: { signInTitle: 'Bienvenido de nuevo', signInSubtitle: 'Inicia sesión para seguir aprendiendo español.', signUpTitle: 'Empieza con poco start', signUpSubtitle: 'Crea una cuenta en menos de un minuto. Dos lecciones son gratis.', name: 'Nombre', email: 'Correo', password: 'Contraseña', createAccount: 'Crear cuenta', signIn: 'Iniciar sesión', continueApple: 'Continuar con Apple', switchToSignUp: '¿Nuevo? Crea una cuenta', switchToSignIn: '¿Ya tienes cuenta? Inicia sesión', passwordShort: 'Usa al menos 6 caracteres.', signUpFailed: 'No se pudo crear la cuenta', signInFailed: 'Error al iniciar sesión', appleFailed: 'Falló el inicio con Apple', languageLabel: 'Quiero la app en' },
    tabs: { home: 'Inicio', learn: 'Aprender', practice: 'Practicar', speak: 'Hablar', profile: 'Perfil' },
    speak: { title: 'Pronunciación', subtitle: 'Toca el micrófono y di la frase en español.', listen: 'Escuchar', tapToSpeak: 'Toca el mic y habla', stop: 'Parar', listening: 'Escuchando… habla claro', youSaid: 'Dijiste', perfect: '¡Perfecto!', great: 'Muy buena pronunciación', close: 'Casi — inténtalo de nuevo', tryAgain: 'No del todo — escucha y reintenta', nextWord: 'Siguiente palabra', unavailable: 'El reconocimiento de voz requiere una build nativa (no Expo Go).', permissionDenied: 'Se necesita permiso de micrófono/voz.', errorGeneric: 'No se escuchó bien. Prueba en un lugar más silencioso.', practiceInLesson: 'Practica decirlo' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Siguiente lección', continueCta: 'Continuar', streak: 'Racha', xp: 'XP', done: 'Hecho', progress: 'Tu progreso', courseCompletion: 'Progreso del curso', unlockTitle: 'Desbloquea el curso completo', unlockBody: 'Mensual o anual — pensado para principiantes.' },
    learn: { title: 'Temario', subtitle: 'A1 para principiantes — vocabulario paso a paso.', unit: 'Unidad {n}' },
    practice: { title: 'Práctica rápida', score: 'Puntos: {score} · {lesson}', emptyTitle: 'Aún no hay ejercicios', emptyBody: 'Termina primero una lección gratis.', goLearn: 'Ir al temario', next: 'Siguiente' },
    profile: { title: 'Perfil', student: 'Alumno', noEmail: 'Sin correo', free: 'Gratis', subscription: 'Suscripción', hasPro: 'Tienes poco start Pro.', noPro: 'Mensual o anual vía App Store / Google Play con RevenueCat.', seePlans: 'Ver planes Pro', restore: 'Restaurar compras', restored: 'Restaurado', restoredBody: 'Pro está activo de nuevo.', noPurchases: 'No hay compras', noPurchasesBody: 'No hay compras anteriores en esta cuenta.', signOut: 'Cerrar sesión', signOutConfirm: '¿Seguro?', language: 'Idioma de la app', days: 'días' },
    paywall: { title: 'poco start Pro', subtitle: 'Aprende español rápido — sin distracciones.', features: ['Temario A1 completo', 'Práctica ilimitada', 'Progreso sincronizado', 'Nuevas lecciones'], yearly: 'Anual', monthly: 'Mensual', flexible: 'Flexible', continuePrice: 'Continuar · {price}', restore: 'Restaurar compras', legal: 'El pago se carga a tu cuenta de Apple/Google. La suscripción se renueva automáticamente salvo cancelación 24 h antes. Gestiona en App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Tu suscripción está activa.', continue: 'Continuar', missingProduct: 'Falta el producto', missingProductBody: 'No se encontró la oferta en RevenueCat.', devMode: 'Modo dev', devModeBody: 'RevenueCat no está configurado. Añade claves en .env.', savings: 'Mejor precio' },
    lesson: { notFound: 'Lección no encontrada', proTitle: 'Lección Pro', proBody: 'Desbloquea con suscripción para continuar.', seePlans: 'Ver planes', startExercises: 'Empezar ejercicios', question: 'Pregunta {n} / {total}', finish: 'Terminar', nextLesson: 'Siguiente lección', unlockNext: 'Desbloquear siguiente', backHome: 'Volver al inicio', great: '¡Muy bien!', correctXp: '{correct}/{total} correctas · +{xp} XP' },
    units: { u1: { title: 'Primeros pasos', description: 'Saludos, números y tú' }, u2: { title: 'En la ciudad', description: 'Comida, lugares y día a día' }, u3: { title: 'Conversación', description: 'Preguntas, tiempo y preferencias' } },
  },
  de: {
    common: { back: 'Zurück', close: 'Schließen', continue: 'Weiter', next: 'Weiter', loading: 'Lädt…', tryAgain: 'Erneut versuchen', free: 'Gratis', pro: 'Pro', cancel: 'Abbrechen' },
    welcome: { tagline: 'Spanisch für Anfänger — schnell, klar und spaßig.', getStarted: 'Loslegen', haveAccount: 'Ich habe schon ein Konto', tryGuest: 'Ohne Konto testen', legal: 'Zum lokalen Monats- oder Jahrespreis. Jederzeit im App Store kündbar.', chooseLanguage: 'App-Sprache' },
    auth: { signInTitle: 'Willkommen zurück', signInSubtitle: 'Melde dich an, um weiter Spanisch zu lernen.', signUpTitle: 'Starte mit poco start', signUpSubtitle: 'Konto in unter einer Minute. Zwei Lektionen gratis.', name: 'Name', email: 'E-Mail', password: 'Passwort', createAccount: 'Konto erstellen', signIn: 'Anmelden', continueApple: 'Mit Apple fortfahren', switchToSignUp: 'Neu hier? Konto erstellen', switchToSignIn: 'Schon ein Konto? Anmelden', passwordShort: 'Mindestens 6 Zeichen.', signUpFailed: 'Konto konnte nicht erstellt werden', signInFailed: 'Anmeldung fehlgeschlagen', appleFailed: 'Apple-Anmeldung fehlgeschlagen', languageLabel: 'Ich möchte die App auf' },
    tabs: { home: 'Start', learn: 'Lernen', practice: 'Üben', speak: 'Sprechen', profile: 'Profil' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Nächste Lektion', continueCta: 'Weiter', streak: 'Serie', xp: 'XP', done: 'Fertig', progress: 'Dein Fortschritt', courseCompletion: 'Kursfortschritt', unlockTitle: 'Ganzen Kurs freischalten', unlockBody: 'Monatlich oder jährlich — für Anfänger gemacht.' },
    learn: { title: 'Lehrplan', subtitle: 'A1 für Anfänger — Wortschatz Schritt für Schritt.', unit: 'Einheit {n}' },
    practice: { title: 'Schnelles Üben', score: 'Punkte: {score} · {lesson}', emptyTitle: 'Noch keine Übungen', emptyBody: 'Schließe zuerst eine gratis Lektion ab.', goLearn: 'Zum Lehrplan', next: 'Weiter' },
    profile: { title: 'Profil', student: 'Lernende/r', noEmail: 'Keine E-Mail', free: 'Gratis', subscription: 'Abo', hasPro: 'Du hast poco start Pro.', noPro: 'Monatlich oder jährlich über App Store / Google Play mit RevenueCat.', seePlans: 'Pro-Pläne ansehen', restore: 'Käufe wiederherstellen', restored: 'Wiederhergestellt', restoredBody: 'Pro ist wieder aktiv.', noPurchases: 'Keine Käufe', noPurchasesBody: 'Keine früheren Käufe für dieses Konto.', signOut: 'Abmelden', signOutConfirm: 'Sicher?', language: 'App-Sprache', days: 'Tage' },
    paywall: { title: 'poco start Pro', subtitle: 'Spanisch schnell lernen — ohne Ablenkung.', features: ['Kompletter A1-Lehrplan', 'Unbegrenztes Üben', 'Fortschritt synchronisiert', 'Neue Lektionen'], yearly: 'Jährlich', monthly: 'Monatlich', flexible: 'Flexibel', continuePrice: 'Weiter · {price}', restore: 'Käufe wiederherstellen', legal: 'Zahlung erfolgt über Apple/Google. Abo verlängert sich automatisch, außer 24 Std. vorher gekündigt. Verwalten im App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Dein Abo ist aktiv.', continue: 'Weiter', missingProduct: 'Produkt fehlt', missingProductBody: 'Angebot in RevenueCat nicht gefunden.', devMode: 'Dev-Modus', devModeBody: 'RevenueCat ist nicht konfiguriert.', savings: 'Bester Preis' },
    lesson: { notFound: 'Lektion nicht gefunden', proTitle: 'Pro-Lektion', proBody: 'Mit Abo freischalten, um weiterzumachen.', seePlans: 'Pläne ansehen', startExercises: 'Übungen starten', question: 'Frage {n} / {total}', finish: 'Fertig', nextLesson: 'Nächste Lektion', unlockNext: 'Nächste freischalten', backHome: 'Zur Startseite', great: '¡Muy bien!', correctXp: '{correct}/{total} richtig · +{xp} XP' },
    units: { u1: { title: 'Erste Schritte', description: 'Begrüßung, Zahlen und du selbst' }, u2: { title: 'In der Stadt', description: 'Essen, Orte und Alltag' }, u3: { title: 'Gespräch', description: 'Fragen, Zeit und Vorlieben' } },
  },
  fr: {
    common: { back: 'Retour', close: 'Fermer', continue: 'Continuer', next: 'Suivant', loading: 'Chargement…', tryAgain: 'Réessayer', free: 'Gratuit', pro: 'Pro', cancel: 'Annuler' },
    welcome: { tagline: 'L’espagnol pour débutants — rapide, clair et fun.', getStarted: 'Commencer', haveAccount: 'J’ai déjà un compte', tryGuest: 'Essayer sans compte', legal: 'Au prix local mensuel ou annuel. Annulez quand vous voulez dans l’App Store.', chooseLanguage: 'Langue de l’app' },
    auth: { signInTitle: 'Bon retour', signInSubtitle: 'Connectez-vous pour continuer l’espagnol.', signUpTitle: 'Commencez avec poco start', signUpSubtitle: 'Créez un compte en moins d’une minute. Deux leçons gratuites.', name: 'Nom', email: 'E-mail', password: 'Mot de passe', createAccount: 'Créer un compte', signIn: 'Se connecter', continueApple: 'Continuer avec Apple', switchToSignUp: 'Nouveau ? Créez un compte', switchToSignIn: 'Déjà un compte ? Connectez-vous', passwordShort: 'Au moins 6 caractères.', signUpFailed: 'Impossible de créer le compte', signInFailed: 'Connexion échouée', appleFailed: 'Connexion Apple échouée', languageLabel: 'Je veux l’app en' },
    tabs: { home: 'Accueil', learn: 'Apprendre', practice: 'Pratiquer', speak: 'Parler', profile: 'Profil' },
    speak: { title: 'Prononciation', subtitle: 'Appuyez sur le micro et dites la phrase en espagnol.', listen: 'Écouter', tapToSpeak: 'Micro puis parlez', stop: 'Stop', listening: 'Écoute… parlez clairement', youSaid: 'Vous avez dit', perfect: 'Parfait !', great: 'Très bonne prononciation', close: 'Presque — réessayez', tryAgain: 'Pas tout à fait — écoutez et réessayez', nextWord: 'Mot suivant', unavailable: 'La reconnaissance vocale nécessite un build natif (pas Expo Go).', permissionDenied: 'Permission micro/voix requise.', errorGeneric: 'Pas entendu. Réessayez dans un endroit plus calme.', practiceInLesson: 'Pratiquer la prononciation' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Prochaine leçon', continueCta: 'Continuer', streak: 'Série', xp: 'XP', done: 'Fait', progress: 'Votre progression', courseCompletion: 'Avancement du cours', unlockTitle: 'Débloquez tout le cours', unlockBody: 'Mensuel ou annuel — pensé pour débutants.' },
    learn: { title: 'Programme', subtitle: 'A1 pour débutants — vocabulaire pas à pas.', unit: 'Unité {n}' },
    practice: { title: 'Pratique rapide', score: 'Score : {score} · {lesson}', emptyTitle: 'Pas encore d’exercices', emptyBody: 'Terminez d’abord une leçon gratuite.', goLearn: 'Voir le programme', next: 'Suivant' },
    profile: { title: 'Profil', student: 'Apprenant', noEmail: 'Pas d’e-mail', free: 'Gratuit', subscription: 'Abonnement', hasPro: 'Vous avez poco start Pro.', noPro: 'Mensuel ou annuel via App Store / Google Play avec RevenueCat.', seePlans: 'Voir les offres Pro', restore: 'Restaurer les achats', restored: 'Restauré', restoredBody: 'Pro est de nouveau actif.', noPurchases: 'Aucun achat', noPurchasesBody: 'Aucun achat précédent pour ce compte.', signOut: 'Se déconnecter', signOutConfirm: 'Êtes-vous sûr ?', language: 'Langue de l’app', days: 'jours' },
    paywall: { title: 'poco start Pro', subtitle: 'Apprenez l’espagnol vite — sans distractions.', features: ['Programme A1 complet', 'Pratique illimitée', 'Progression synchronisée', 'Nouvelles leçons'], yearly: 'Annuel', monthly: 'Mensuel', flexible: 'Flexible', continuePrice: 'Continuer · {price}', restore: 'Restaurer les achats', legal: 'Le paiement est débité sur votre compte Apple/Google. L’abonnement se renouvelle sauf annulation 24 h avant. Gérez dans l’App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Votre abonnement est actif.', continue: 'Continuer', missingProduct: 'Produit manquant', missingProductBody: 'Offre introuvable dans RevenueCat.', devMode: 'Mode dev', devModeBody: 'RevenueCat n’est pas configuré.', savings: 'Meilleur prix' },
    lesson: { notFound: 'Leçon introuvable', proTitle: 'Leçon Pro', proBody: 'Débloquez avec un abonnement pour continuer.', seePlans: 'Voir les offres', startExercises: 'Commencer les exercices', question: 'Question {n} / {total}', finish: 'Terminer', nextLesson: 'Leçon suivante', unlockNext: 'Débloquer la suivante', backHome: 'Retour à l’accueil', great: '¡Muy bien!', correctXp: '{correct}/{total} correctes · +{xp} XP' },
    units: { u1: { title: 'Premiers pas', description: 'Salutations, chiffres et soi' }, u2: { title: 'En ville', description: 'Nourriture, lieux et quotidien' }, u3: { title: 'Conversation', description: 'Questions, temps et préférences' } },
  },
  pt: {
    common: { back: 'Voltar', close: 'Fechar', continue: 'Continuar', next: 'Seguinte', loading: 'A carregar…', tryAgain: 'Tentar de novo', free: 'Grátis', pro: 'Pro', cancel: 'Cancelar' },
    welcome: { tagline: 'Espanhol para iniciantes — rápido, claro e divertido.', getStarted: 'Começar', haveAccount: 'Já tenho conta', tryGuest: 'Experimentar sem conta', legal: 'Ao preço local mensal ou anual. Cancele quando quiser na App Store.', chooseLanguage: 'Idioma da app' },
    auth: { signInTitle: 'Bem-vindo de volta', signInSubtitle: 'Inicie sessão para continuar a aprender espanhol.', signUpTitle: 'Comece com poco start', signUpSubtitle: 'Crie uma conta em menos de um minuto. Duas lições grátis.', name: 'Nome', email: 'E-mail', password: 'Palavra-passe', createAccount: 'Criar conta', signIn: 'Iniciar sessão', continueApple: 'Continuar com Apple', switchToSignUp: 'Novo aqui? Criar conta', switchToSignIn: 'Já tem conta? Iniciar sessão', passwordShort: 'Use pelo menos 6 caracteres.', signUpFailed: 'Não foi possível criar a conta', signInFailed: 'Falha no início de sessão', appleFailed: 'Falha no Apple', languageLabel: 'Quero a app em' },
    tabs: { home: 'Início', learn: 'Aprender', practice: 'Praticar', speak: 'Falar', profile: 'Perfil' },
    speak: { title: 'Pronúncia', subtitle: 'Toque no microfone e diga a frase em espanhol.', listen: 'Ouvir', tapToSpeak: 'Toque no mic e fale', stop: 'Parar', listening: 'A ouvir… fale claramente', youSaid: 'Disse', perfect: 'Perfeito!', great: 'Ótima pronúncia', close: 'Quase — tente de novo', tryAgain: 'Ainda não — ouça e tente outra vez', nextWord: 'Próxima palavra', unavailable: 'O reconhecimento de voz precisa de build nativa (não Expo Go).', permissionDenied: 'É preciso permissão de microfone/voz.', errorGeneric: 'Não ouvi bem. Tente num sítio mais calmo.', practiceInLesson: 'Praticar a pronúncia' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Próxima lição', continueCta: 'Continuar', streak: 'Sequência', xp: 'XP', done: 'Feito', progress: 'O seu progresso', courseCompletion: 'Conclusão do curso', unlockTitle: 'Desbloqueie o curso completo', unlockBody: 'Mensal ou anual — feito para iniciantes.' },
    learn: { title: 'Plano de estudos', subtitle: 'A1 para iniciantes — vocabulário passo a passo.', unit: 'Unidade {n}' },
    practice: { title: 'Prática rápida', score: 'Pontos: {score} · {lesson}', emptyTitle: 'Ainda sem exercícios', emptyBody: 'Termine primeiro uma lição grátis.', goLearn: 'Ir ao plano', next: 'Seguinte' },
    profile: { title: 'Perfil', student: 'Aluno', noEmail: 'Sem e-mail', free: 'Grátis', subscription: 'Subscrição', hasPro: 'Tem poco start Pro.', noPro: 'Mensal ou anual via App Store / Google Play com RevenueCat.', seePlans: 'Ver planos Pro', restore: 'Restaurar compras', restored: 'Restaurado', restoredBody: 'Pro está ativo novamente.', noPurchases: 'Sem compras', noPurchasesBody: 'Sem compras anteriores nesta conta.', signOut: 'Terminar sessão', signOutConfirm: 'Tem a certeza?', language: 'Idioma da app', days: 'dias' },
    paywall: { title: 'poco start Pro', subtitle: 'Aprenda espanhol depressa — sem distrações.', features: ['Currículo A1 completo', 'Prática ilimitada', 'Progresso sincronizado', 'Novas lições'], yearly: 'Anual', monthly: 'Mensal', flexible: 'Flexível', continuePrice: 'Continuar · {price}', restore: 'Restaurar compras', legal: 'O pagamento é cobrado na conta Apple/Google. A subscrição renova-se automaticamente salvo cancelamento 24 h antes. Faça a gestão na App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'A sua subscrição está ativa.', continue: 'Continuar', missingProduct: 'Produto em falta', missingProductBody: 'Oferta não encontrada no RevenueCat.', devMode: 'Modo dev', devModeBody: 'RevenueCat não está configurado.', savings: 'Melhor preço' },
    lesson: { notFound: 'Lição não encontrada', proTitle: 'Lição Pro', proBody: 'Desbloqueie com subscrição para continuar.', seePlans: 'Ver planos', startExercises: 'Começar exercícios', question: 'Pergunta {n} / {total}', finish: 'Concluir', nextLesson: 'Próxima lição', unlockNext: 'Desbloquear seguinte', backHome: 'Voltar ao início', great: '¡Muy bien!', correctXp: '{correct}/{total} corretas · +{xp} XP' },
    units: { u1: { title: 'Primeiros passos', description: 'Saudações, números e você' }, u2: { title: 'Na cidade', description: 'Comida, lugares e dia a dia' }, u3: { title: 'Conversação', description: 'Perguntas, tempo e preferências' } },
  },
  it: {
    common: { back: 'Indietro', close: 'Chiudi', continue: 'Continua', next: 'Avanti', loading: 'Caricamento…', tryAgain: 'Riprova', free: 'Gratis', pro: 'Pro', cancel: 'Annulla' },
    welcome: { tagline: 'Spagnolo per principianti — veloce, chiaro e divertente.', getStarted: 'Inizia', haveAccount: 'Ho già un account', tryGuest: 'Prova senza account', legal: 'Al prezzo locale mensile o annuale. Annulla quando vuoi dall’App Store.', chooseLanguage: 'Lingua dell’app' },
    auth: { signInTitle: 'Bentornato', signInSubtitle: 'Accedi per continuare a imparare lo spagnolo.', signUpTitle: 'Inizia con poco start', signUpSubtitle: 'Crea un account in meno di un minuto. Due lezioni gratis.', name: 'Nome', email: 'Email', password: 'Password', createAccount: 'Crea account', signIn: 'Accedi', continueApple: 'Continua con Apple', switchToSignUp: 'Nuovo? Crea un account', switchToSignIn: 'Hai già un account? Accedi', passwordShort: 'Almeno 6 caratteri.', signUpFailed: 'Impossibile creare l’account', signInFailed: 'Accesso non riuscito', appleFailed: 'Accesso Apple non riuscito', languageLabel: 'Voglio l’app in' },
    tabs: { home: 'Home', learn: 'Impara', practice: 'Pratica', speak: 'Parla', profile: 'Profilo' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Prossima lezione', continueCta: 'Continua', streak: 'Serie', xp: 'XP', done: 'Fatto', progress: 'I tuoi progressi', courseCompletion: 'Completamento corso', unlockTitle: 'Sblocca tutto il corso', unlockBody: 'Mensile o annuale — pensato per principianti.' },
    learn: { title: 'Programma', subtitle: 'A1 per principianti — vocabolario passo dopo passo.', unit: 'Unità {n}' },
    practice: { title: 'Pratica veloce', score: 'Punteggio: {score} · {lesson}', emptyTitle: 'Nessun esercizio ancora', emptyBody: 'Completa prima una lezione gratis.', goLearn: 'Vai al programma', next: 'Avanti' },
    profile: { title: 'Profilo', student: 'Studente', noEmail: 'Nessuna email', free: 'Gratis', subscription: 'Abbonamento', hasPro: 'Hai poco start Pro.', noPro: 'Mensile o annuale via App Store / Google Play con RevenueCat.', seePlans: 'Vedi piani Pro', restore: 'Ripristina acquisti', restored: 'Ripristinato', restoredBody: 'Pro è di nuovo attivo.', noPurchases: 'Nessun acquisto', noPurchasesBody: 'Nessun acquisto precedente per questo account.', signOut: 'Esci', signOutConfirm: 'Sei sicuro?', language: 'Lingua dell’app', days: 'giorni' },
    paywall: { title: 'poco start Pro', subtitle: 'Impara lo spagnolo in fretta — senza distrazioni.', features: ['Curriculum A1 completo', 'Pratica illimitata', 'Progressi sincronizzati', 'Nuove lezioni'], yearly: 'Annuale', monthly: 'Mensile', flexible: 'Flessibile', continuePrice: 'Continua · {price}', restore: 'Ripristina acquisti', legal: 'Il pagamento viene addebitato sull’account Apple/Google. L’abbonamento si rinnova automaticamente salvo disdetta 24 ore prima. Gestisci in App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Il tuo abbonamento è attivo.', continue: 'Continua', missingProduct: 'Prodotto mancante', missingProductBody: 'Offerta non trovata in RevenueCat.', devMode: 'Modalità dev', devModeBody: 'RevenueCat non è configurato.', savings: 'Miglior prezzo' },
    lesson: { notFound: 'Lezione non trovata', proTitle: 'Lezione Pro', proBody: 'Sblocca con abbonamento per continuare.', seePlans: 'Vedi piani', startExercises: 'Inizia esercizi', question: 'Domanda {n} / {total}', finish: 'Finisci', nextLesson: 'Lezione successiva', unlockNext: 'Sblocca successiva', backHome: 'Torna alla home', great: '¡Muy bien!', correctXp: '{correct}/{total} corrette · +{xp} XP' },
    units: { u1: { title: 'Primi passi', description: 'Saluti, numeri e te stesso' }, u2: { title: 'In città', description: 'Cibo, luoghi e quotidianità' }, u3: { title: 'Conversazione', description: 'Domande, tempo e preferenze' } },
  },
  nl: {
    common: { back: 'Terug', close: 'Sluiten', continue: 'Doorgaan', next: 'Volgende', loading: 'Laden…', tryAgain: 'Opnieuw proberen', free: 'Gratis', pro: 'Pro', cancel: 'Annuleren' },
    welcome: { tagline: 'Spaans voor beginners — snel, duidelijk en leuk.', getStarted: 'Aan de slag', haveAccount: 'Ik heb al een account', tryGuest: 'Probeer zonder account', legal: 'Tegen lokale maand- of jaarpijs. Altijd opzegbaar via de App Store.', chooseLanguage: 'App-taal' },
    auth: { signInTitle: 'Welkom terug', signInSubtitle: 'Log in om Spaans te blijven leren.', signUpTitle: 'Start met poco start', signUpSubtitle: 'Maak in minder dan een minuut een account. Twee lessen gratis.', name: 'Naam', email: 'E-mail', password: 'Wachtwoord', createAccount: 'Account maken', signIn: 'Inloggen', continueApple: 'Doorgaan met Apple', switchToSignUp: 'Nieuw hier? Account maken', switchToSignIn: 'Al een account? Inloggen', passwordShort: 'Minimaal 6 tekens.', signUpFailed: 'Account aanmaken mislukt', signInFailed: 'Inloggen mislukt', appleFailed: 'Apple-login mislukt', languageLabel: 'Ik wil de app in' },
    tabs: { home: 'Home', learn: 'Leren', practice: 'Oefenen', speak: 'Spreken', profile: 'Profiel' },
    speak: { title: 'Uitspraak', subtitle: 'Tik op de microfoon en zeg de Spaanse zin.', listen: 'Beluisteren', tapToSpeak: 'Tik mic & spreek', stop: 'Stop', listening: 'Luistert… spreek duidelijk', youSaid: 'Je zei', perfect: 'Perfect!', great: 'Goede uitspraak', close: 'Bijna — probeer opnieuw', tryAgain: 'Nog niet — luister en probeer weer', nextWord: 'Volgend woord', unavailable: 'Spraakherkenning vereist een native build (niet Expo Go).', permissionDenied: 'Microfoon-/spraaktoestemming nodig.', errorGeneric: 'Niet verstaan. Probeer op een stillere plek.', practiceInLesson: 'Oefen de uitspraak' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Volgende les', continueCta: 'Doorgaan', streak: 'Reeks', xp: 'XP', done: 'Klaar', progress: 'Jouw voortgang', courseCompletion: 'Cursusvoortgang', unlockTitle: 'Ontgrendel de hele cursus', unlockBody: 'Maandelijks of jaarlijks — gemaakt voor beginners.' },
    learn: { title: 'Leerplan', subtitle: 'A1 voor beginners — vocabulaire stap voor stap.', unit: 'Eenheid {n}' },
    practice: { title: 'Snel oefenen', score: 'Score: {score} · {lesson}', emptyTitle: 'Nog geen oefeningen', emptyBody: 'Rond eerst een gratis les af.', goLearn: 'Naar leerplan', next: 'Volgende' },
    profile: { title: 'Profiel', student: 'Leerling', noEmail: 'Geen e-mail', free: 'Gratis', subscription: 'Abonnement', hasPro: 'Je hebt poco start Pro.', noPro: 'Maandelijks of jaarlijks via App Store / Google Play met RevenueCat.', seePlans: 'Bekijk Pro-plannen', restore: 'Aankopen herstellen', restored: 'Hersteld', restoredBody: 'Pro is weer actief.', noPurchases: 'Geen aankopen', noPurchasesBody: 'Geen eerdere aankopen voor dit account.', signOut: 'Uitloggen', signOutConfirm: 'Weet je het zeker?', language: 'App-taal', days: 'dagen' },
    paywall: { title: 'poco start Pro', subtitle: 'Leer Spaans snel — zonder afleiding.', features: ['Volledig A1-leerplan', 'Onbeperkt oefenen', 'Voortgang gesynchroniseerd', 'Nieuwe lessen'], yearly: 'Jaarlijks', monthly: 'Maandelijks', flexible: 'Flexibel', continuePrice: 'Doorgaan · {price}', restore: 'Aankopen herstellen', legal: 'Betaling via Apple/Google. Abonnement verlengt automatisch tenzij 24 uur van tevoren opgezegd. Beheer in App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Je abonnement is actief.', continue: 'Doorgaan', missingProduct: 'Product ontbreekt', missingProductBody: 'Aanbieding niet gevonden in RevenueCat.', devMode: 'Dev-modus', devModeBody: 'RevenueCat is niet geconfigureerd.', savings: 'Beste prijs' },
    lesson: { notFound: 'Les niet gevonden', proTitle: 'Pro-les', proBody: 'Ontgrendel met abonnement om door te gaan.', seePlans: 'Bekijk plannen', startExercises: 'Start oefeningen', question: 'Vraag {n} / {total}', finish: 'Afronden', nextLesson: 'Volgende les', unlockNext: 'Volgende ontgrendelen', backHome: 'Terug naar home', great: '¡Muy bien!', correctXp: '{correct}/{total} goed · +{xp} XP' },
    units: { u1: { title: 'Eerste stappen', description: 'Begroetingen, cijfers en jezelf' }, u2: { title: 'In de stad', description: 'Eten, plekken en dagelijks leven' }, u3: { title: 'Gesprek', description: 'Vragen, tijd en voorkeuren' } },
  },
  sv: {
    common: { back: 'Tillbaka', close: 'Stäng', continue: 'Fortsätt', next: 'Nästa', loading: 'Laddar…', tryAgain: 'Försök igen', free: 'Gratis', pro: 'Pro', cancel: 'Avbryt' },
    welcome: { tagline: 'Spanska för nybörjare — snabbt, tydligt och kul.', getStarted: 'Kom igång', haveAccount: 'Jag har redan konto', tryGuest: 'Prova utan konto', legal: 'Till lokalt månads- eller årspris. Avsluta när som helst via App Store.', chooseLanguage: 'Appspråk' },
    auth: { signInTitle: 'Välkommen tillbaka', signInSubtitle: 'Logga in för att fortsätta lära dig spanska.', signUpTitle: 'Börja med poco start', signUpSubtitle: 'Skapa konto på under en minut. Två lektioner är gratis.', name: 'Namn', email: 'E-post', password: 'Lösenord', createAccount: 'Skapa konto', signIn: 'Logga in', continueApple: 'Fortsätt med Apple', switchToSignUp: 'Ny här? Skapa konto', switchToSignIn: 'Har du konto? Logga in', passwordShort: 'Minst 6 tecken.', signUpFailed: 'Kunde inte skapa konto', signInFailed: 'Inloggning misslyckades', appleFailed: 'Apple-inloggning misslyckades', languageLabel: 'Jag vill ha appen på' },
    tabs: { home: 'Hem', learn: 'Lär', practice: 'Öva', speak: 'Tala', profile: 'Profil' },
    speak: { title: 'Uttal', subtitle: 'Tryck på mikrofonen och säg den spanska frasen.', listen: 'Lyssna', tapToSpeak: 'Tryck mic & tala', stop: 'Stopp', listening: 'Lyssnar… tala tydligt', youSaid: 'Du sa', perfect: 'Perfekt!', great: 'Bra uttal', close: 'Nästan — försök igen', tryAgain: 'Inte riktigt — lyssna och försök igen', nextWord: 'Nästa ord', unavailable: 'Taligenkänning kräver native build (inte Expo Go).', permissionDenied: 'Mikrofon-/taletillstånd krävs.', errorGeneric: 'Hörde inte. Försök på en tystare plats.', practiceInLesson: 'Öva uttalet' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Nästa lektion', continueCta: 'Fortsätt', streak: 'Streak', xp: 'XP', done: 'Klar', progress: 'Din progress', courseCompletion: 'Kurskomplettering', unlockTitle: 'Lås upp hela kursen', unlockBody: 'Månads- eller årspris — gjord för nybörjare.' },
    learn: { title: 'Läroplan', subtitle: 'A1 för nybörjare — bygg ordförråd steg för steg.', unit: 'Enhet {n}' },
    practice: { title: 'Snabbövning', score: 'Poäng: {score} · {lesson}', emptyTitle: 'Inga övningar än', emptyBody: 'Slutför en gratis lektion först.', goLearn: 'Gå till läroplan', next: 'Nästa' },
    profile: { title: 'Profil', student: 'Elev', noEmail: 'Ingen e-post', free: 'Gratis', subscription: 'Prenumeration', hasPro: 'Du har poco start Pro.', noPro: 'Månads- eller årsvis via App Store / Google Play med RevenueCat.', seePlans: 'Se Pro-planer', restore: 'Återställ köp', restored: 'Återställt', restoredBody: 'Pro är aktivt igen.', noPurchases: 'Inga köp', noPurchasesBody: 'Inga tidigare köp för det här kontot.', signOut: 'Logga ut', signOutConfirm: 'Är du säker?', language: 'Appspråk', days: 'dagar' },
    paywall: { title: 'poco start Pro', subtitle: 'Lär dig spanska snabbt — utan distraktioner.', features: ['Hela A1-läroplanen', 'Obegränsad övning', 'Progress synkad', 'Nya lektioner'], yearly: 'Årlig', monthly: 'Månadsvis', flexible: 'Flexibelt', continuePrice: 'Fortsätt · {price}', restore: 'Återställ köp', legal: 'Betalning debiteras ditt Apple-/Google-konto. Prenumerationen förnyas automatiskt om den inte sägs upp senast 24 timmar innan. Hantera i App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Din prenumeration är aktiv.', continue: 'Fortsätt', missingProduct: 'Produkt saknas', missingProductBody: 'Erbjudandet hittades inte i RevenueCat.', devMode: 'Dev-läge', devModeBody: 'RevenueCat är inte konfigurerat.', savings: 'Bästa pris' },
    lesson: { notFound: 'Lektion hittades inte', proTitle: 'Pro-lektion', proBody: 'Lås upp med prenumeration för att fortsätta.', seePlans: 'Se planer', startExercises: 'Starta övningar', question: 'Fråga {n} / {total}', finish: 'Slutför', nextLesson: 'Nästa lektion', unlockNext: 'Lås upp nästa', backHome: 'Tillbaka till hem', great: '¡Muy bien!', correctXp: '{correct}/{total} rätt · +{xp} XP' },
    units: { u1: { title: 'Första stegen', description: 'Hälsningar, siffror och dig själv' }, u2: { title: 'I staden', description: 'Mat, platser och vardag' }, u3: { title: 'Samtal', description: 'Frågor, tid och preferenser' } },
  },
  da: {
    common: { back: 'Tilbage', close: 'Luk', continue: 'Fortsæt', next: 'Næste', loading: 'Indlæser…', tryAgain: 'Prøv igen', free: 'Gratis', pro: 'Pro', cancel: 'Annuller' },
    welcome: { tagline: 'Spansk for begyndere — hurtigt, klart og sjovt.', getStarted: 'Kom i gang', haveAccount: 'Jeg har allerede en konto', tryGuest: 'Prøv uden konto', legal: 'Til lokal måneds- eller årspris. Opsig når som helst via App Store.', chooseLanguage: 'Appsprog' },
    auth: { signInTitle: 'Velkommen tilbage', signInSubtitle: 'Log ind for at fortsætte med spansk.', signUpTitle: 'Start med poco start', signUpSubtitle: 'Opret konto på under et minut. To lektioner er gratis.', name: 'Navn', email: 'E-mail', password: 'Adgangskode', createAccount: 'Opret konto', signIn: 'Log ind', continueApple: 'Fortsæt med Apple', switchToSignUp: 'Ny her? Opret konto', switchToSignIn: 'Har du konto? Log ind', passwordShort: 'Mindst 6 tegn.', signUpFailed: 'Kunne ikke oprette konto', signInFailed: 'Login mislykkedes', appleFailed: 'Apple-login mislykkedes', languageLabel: 'Jeg vil have appen på' },
    tabs: { home: 'Hjem', learn: 'Lær', practice: 'Øv', speak: 'Tal', profile: 'Profil' },
    speak: { title: 'Udtale', subtitle: 'Tryk på mikrofonen og sig den spanske sætning.', listen: 'Lyt', tapToSpeak: 'Tryk mic & tal', stop: 'Stop', listening: 'Lytter… tal tydeligt', youSaid: 'Du sagde', perfect: 'Perfekt!', great: 'God udtale', close: 'Næsten — prøv igen', tryAgain: 'Ikke helt — lyt og prøv igen', nextWord: 'Næste ord', unavailable: 'Talegenkendelse kræver native build (ikke Expo Go).', permissionDenied: 'Mikrofon-/taletilladelse kræves.', errorGeneric: 'Hørte det ikke. Prøv et roligere sted.', practiceInLesson: 'Øv udtalen' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Næste lektion', continueCta: 'Fortsæt', streak: 'Streak', xp: 'XP', done: 'Færdig', progress: 'Din fremgang', courseCompletion: 'Kursusfremskridt', unlockTitle: 'Lås hele kurset op', unlockBody: 'Månedligt eller årligt — lavet til begyndere.' },
    learn: { title: 'Læreplan', subtitle: 'A1 for begyndere — ordforråd trin for trin.', unit: 'Enhed {n}' },
    practice: { title: 'Hurtig øvelse', score: 'Point: {score} · {lesson}', emptyTitle: 'Ingen øvelser endnu', emptyBody: 'Fuldfør først en gratis lektion.', goLearn: 'Gå til læreplan', next: 'Næste' },
    profile: { title: 'Profil', student: 'Elev', noEmail: 'Ingen e-mail', free: 'Gratis', subscription: 'Abonnement', hasPro: 'Du har poco start Pro.', noPro: 'Månedligt eller årligt via App Store / Google Play med RevenueCat.', seePlans: 'Se Pro-planer', restore: 'Gendan køb', restored: 'Gendannet', restoredBody: 'Pro er aktiv igen.', noPurchases: 'Ingen køb', noPurchasesBody: 'Ingen tidligere køb for denne konto.', signOut: 'Log ud', signOutConfirm: 'Er du sikker?', language: 'Appsprog', days: 'dage' },
    paywall: { title: 'poco start Pro', subtitle: 'Lær spansk hurtigt — uden distraktioner.', features: ['Hele A1-læreplanen', 'Ubegrænset øvelse', 'Fremgang synkroniseret', 'Nye lektioner'], yearly: 'Årligt', monthly: 'Månedligt', flexible: 'Fleksibelt', continuePrice: 'Fortsæt · {price}', restore: 'Gendan køb', legal: 'Betaling trækkes fra din Apple-/Google-konto. Abonnement fornyes automatisk, medmindre det opsiges senest 24 timer før. Administrer i App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Dit abonnement er aktivt.', continue: 'Fortsæt', missingProduct: 'Produkt mangler', missingProductBody: 'Tilbud ikke fundet i RevenueCat.', devMode: 'Dev-tilstand', devModeBody: 'RevenueCat er ikke konfigureret.', savings: 'Bedste pris' },
    lesson: { notFound: 'Lektion ikke fundet', proTitle: 'Pro-lektion', proBody: 'Lås op med abonnement for at fortsætte.', seePlans: 'Se planer', startExercises: 'Start øvelser', question: 'Spørgsmål {n} / {total}', finish: 'Afslut', nextLesson: 'Næste lektion', unlockNext: 'Lås næste op', backHome: 'Tilbage til hjem', great: '¡Muy bien!', correctXp: '{correct}/{total} rigtige · +{xp} XP' },
    units: { u1: { title: 'Første skridt', description: 'Hilsner, tal og dig selv' }, u2: { title: 'I byen', description: 'Mad, steder og hverdag' }, u3: { title: 'Samtale', description: 'Spørgsmål, tid og præferencer' } },
  },
  pl: {
    common: { back: 'Wstecz', close: 'Zamknij', continue: 'Kontynuuj', next: 'Dalej', loading: 'Ładowanie…', tryAgain: 'Spróbuj ponownie', free: 'Za darmo', pro: 'Pro', cancel: 'Anuluj' },
    welcome: { tagline: 'Hiszpański dla początkujących — szybko, jasno i przyjemnie.', getStarted: 'Zaczynamy', haveAccount: 'Mam już konto', tryGuest: 'Wypróbuj bez konta', legal: 'W lokalnej cenie miesięcznej lub rocznej. Anuluj kiedy chcesz w App Store.', chooseLanguage: 'Język aplikacji' },
    auth: { signInTitle: 'Witaj ponownie', signInSubtitle: 'Zaloguj się, by dalej uczyć się hiszpańskiego.', signUpTitle: 'Zacznij z poco start', signUpSubtitle: 'Załóż konto w mniej niż minutę. Dwie lekcje za darmo.', name: 'Imię', email: 'E-mail', password: 'Hasło', createAccount: 'Utwórz konto', signIn: 'Zaloguj się', continueApple: 'Kontynuuj z Apple', switchToSignUp: 'Nowy? Utwórz konto', switchToSignIn: 'Masz konto? Zaloguj się', passwordShort: 'Co najmniej 6 znaków.', signUpFailed: 'Nie udało się utworzyć konta', signInFailed: 'Logowanie nie powiodło się', appleFailed: 'Logowanie Apple nie powiodło się', languageLabel: 'Chcę aplikację po' },
    tabs: { home: 'Start', learn: 'Nauka', practice: 'Ćwiczenia', speak: 'Mów', profile: 'Profil' },
    speak: { title: 'Wymowa', subtitle: 'Dotknij mikrofonu i powiedz hiszpańską frazę.', listen: 'Posłuchaj', tapToSpeak: 'Mic i mów', stop: 'Stop', listening: 'Słucham… mów wyraźnie', youSaid: 'Powiedziałeś', perfect: 'Idealnie!', great: 'Świetna wymowa', close: 'Prawie — spróbuj ponownie', tryAgain: 'Nie do końca — posłuchaj i spróbuj', nextWord: 'Następne słowo', unavailable: 'Rozpoznawanie mowy wymaga natywnego builda (nie Expo Go).', permissionDenied: 'Wymagane uprawnienie do mikrofonu/mowy.', errorGeneric: 'Nie usłyszano. Spróbuj w cichszym miejscu.', practiceInLesson: 'Ćwicz wymowę' },
    home: { greeting: '¡Hola!', greetingNamed: '¡Hola, {name}!', nextLesson: 'Następna lekcja', continueCta: 'Kontynuuj', streak: 'Seria', xp: 'XP', done: 'Gotowe', progress: 'Twój postęp', courseCompletion: 'Ukończenie kursu', unlockTitle: 'Odblokuj cały kurs', unlockBody: 'Miesięcznie lub rocznie — stworzone dla początkujących.' },
    learn: { title: 'Program', subtitle: 'A1 dla początkujących — słownictwo krok po kroku.', unit: 'Jednostka {n}' },
    practice: { title: 'Szybkie ćwiczenia', score: 'Punkty: {score} · {lesson}', emptyTitle: 'Brak ćwiczeń', emptyBody: 'Najpierw ukończ darmową lekcję.', goLearn: 'Przejdź do programu', next: 'Dalej' },
    profile: { title: 'Profil', student: 'Uczeń', noEmail: 'Brak e-maila', free: 'Za darmo', subscription: 'Subskrypcja', hasPro: 'Masz poco start Pro.', noPro: 'Miesięcznie lub rocznie przez App Store / Google Play z RevenueCat.', seePlans: 'Zobacz plany Pro', restore: 'Przywróć zakupy', restored: 'Przywrócono', restoredBody: 'Pro jest znowu aktywne.', noPurchases: 'Brak zakupów', noPurchasesBody: 'Brak wcześniejszych zakupów dla tego konta.', signOut: 'Wyloguj', signOutConfirm: 'Na pewno?', language: 'Język aplikacji', days: 'dni' },
    paywall: { title: 'poco start Pro', subtitle: 'Ucz się hiszpańskiego szybko — bez rozpraszaczy.', features: ['Pełny program A1', 'Ćwiczenia bez limitu', 'Postęp zsynchronizowany', 'Nowe lekcje'], yearly: 'Rocznie', monthly: 'Miesięcznie', flexible: 'Elastycznie', continuePrice: 'Kontynuuj · {price}', restore: 'Przywróć zakupy', legal: 'Płatność obciąża konto Apple/Google. Subskrypcja odnawia się automatycznie, chyba że anulujesz na 24 h wcześniej. Zarządzaj w App Store / Play Store.', welcomePro: '¡Bienvenido a Pro!', welcomeProBody: 'Twoja subskrypcja jest aktywna.', continue: 'Kontynuuj', missingProduct: 'Brak produktu', missingProductBody: 'Nie znaleziono oferty w RevenueCat.', devMode: 'Tryb dev', devModeBody: 'RevenueCat nie jest skonfigurowany.', savings: 'Najlepsza cena' },
    lesson: { notFound: 'Nie znaleziono lekcji', proTitle: 'Lekcja Pro', proBody: 'Odblokuj subskrypcją, by kontynuować.', seePlans: 'Zobacz plany', startExercises: 'Zacznij ćwiczenia', question: 'Pytanie {n} / {total}', finish: 'Zakończ', nextLesson: 'Następna lekcja', unlockNext: 'Odblokuj następną', backHome: 'Wróć do startu', great: '¡Muy bien!', correctXp: '{correct}/{total} poprawnych · +{xp} XP' },
    units: { u1: { title: 'Pierwsze kroki', description: 'Powitania, liczby i Ty' }, u2: { title: 'W mieście', description: 'Jedzenie, miejsca i codzienność' }, u3: { title: 'Rozmowa', description: 'Pytania, czas i preferencje' } },
  },
};

for (const [code, data] of Object.entries(packs)) {
  const body = `import type { TranslationTree } from '../types';
import en from './en';

/** UI in ${code}; lesson content falls back to English until fully localized. */
const ${code}: TranslationTree = {
  ...en,
  ...(${JSON.stringify(data, null, 2)}),
  lessons: en.lessons,
};

export default ${code};
`;
  fs.writeFileSync(path.join(outDir, `${code}.ts`), body);
  console.log('wrote', code);
}
